apps/blog/urls.py
# coding=utf-8
from django.conf.urls import url
from zinnia.views.entries import EntryDetail
from ..blog.views import entry_create, upload, get_uploader_template, get_list

urlpatterns = [
    url(r'^entry/add/$', entry_create, name='entry_create'),
    url(r'^entry/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$', EntryDetail.as_view(),
        name='entry_detail'),
    url(r'^entry/upload/', upload, name='upload'),
    url(r"^entry/get_images/(?P<offset>\d+)?", get_list, name='get_image_list'),
    url(r'^entry/get_template/', get_uploader_template, name='get_uploader_template'),
]

wedding/urls.py
from django.views import static
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django_xmlrpc import views
from apps.core.views import HomePageView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^weblog/', include('apps.blog.urls', namespace='blog')),
    url(r'^weblog/', include('zinnia.urls', namespace='zinnia')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^xmlrpc/$', views.handle_xmlrpc),
    url(r'^accounts/', include('apps.accounts.urls')),
    url(r'^vendors/', include('apps.vendors.urls')),
    url(r'^payments/', include('apps.payments.urls')),
    url(r'^docs/', include('rest_framework_docs.urls')),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT})
]

templates/zinnia/author_list.html
{% extends "zinnia/base.html" %}
{% load i18n %}

{% block meta-description %}{% trans "Author list" %}{% endblock meta-description %}

{% block title %}{% trans "Authors" %}{% endblock title %}

{% block body-class %}author-list{% endblock body-class %}

{% block content %}
<h1>{% trans "Author list" %}</h1>

<ul>
  {% for object in object_list %}
  <li class="vcard">
    <a href="{{ object.get_absolute_url }}"
       title="{% blocktrans with author=object %}Show all {{ author }}'s entries{% endblocktrans %}"
       class="fn url{% if not author.get_full_name %} nickname{% endif %}">{{ object }}</a>
    {% blocktrans count entry_count=object.count_entries_published %}{{ entry_count }} entry{% plural %}{{ entry_count }} entries{% endblocktrans %}
  </li>
  {% empty %}
  <li>
    {% trans "No authors yet." %}
  </li>
  {% endfor %}
</ul>
{% endblock content %}

templates/zinnia/base.html
{% extends "zinnia/skeleton.html" %}
{% load i18n %}
{% load zinnia %}

{% block meta-keywords %}{% get_tags as entry_tags %}{{ entry_tags|join:", "}}{% endblock meta-keywords %}

{% block meta %}
    <meta name="generator" content="Zinnia {{ ZINNIA_VERSION }}" />
{% endblock meta %}

{% block link %}
    <link rel="index" href="{% url 'zinnia:entry_archive_index' %}" />
    <link rel="author" type="text/plain" href="{% url 'zinnia:humans' %}" />
    <link rel="EditURI" type="application/rsd+xml" href="{% url 'zinnia:rsd' %}" />
    <link rel="wlwmanifest" type="application/wlwmanifest+xml" href="{% url 'zinnia:wlwmanifest' %}" />
    <link rel="search" type="application/opensearchdescription+xml" title="Zinnia's Weblog" href="{% url 'zinnia:opensearch' %}" />
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS feed of last entries" %}" href="{% url 'zinnia:entry_feed' %}" />
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS feed of last discussions" %}" href="{% url 'zinnia:discussion_feed' %}" />
    {% get_archives_entries "zinnia/tags/entries_archives_link.html" %}
{% endblock link %}

{% block breadcrumbs %}
  {% zinnia_breadcrumbs %}
{% endblock breadcrumbs %}

{% block sidebar %}
<aside id="widget-welcome" class="widget">
  <h3>{% trans "Welcome!" %}</h3>
  <p>
    {% trans "This simple theme is the default appearance of Zinnia." %}
  </p>
  <p>
    {% trans "Don't hesitate to override the template <strong>zinnia/base.html</strong> to start <a href='http://docs.django-blog-zinnia.com/en/latest/how-to/customize_look_and_feel.html'>customizing your Weblog</a>." %}
  </p>
</aside>
<aside id="widget-categories" class="widget">
  <h3>
    <a href="{% url 'zinnia:category_list' %}">{% trans "Categories" %}</a>
  </h3>
  {% get_categories %}
</aside>
<aside id="widget-authors" class="widget">
  <h3>
    <a href="{% url 'zinnia:author_list' %}">{% trans "Authors" %}</a>
  </h3>
  {% get_authors %}
</aside>
<aside id="widget-calendar" class="widget">
  <h3>{% trans "Calendar" %}</h3>
  {% get_calendar_entries %}
</aside>
<aside id="widget-tags" class="widget">
  <h3>
    <a href="{% url 'zinnia:tag_list' %}">{% trans "Tags" %}</a>
  </h3>
  {% get_tag_cloud %}
</aside>
<aside id="widget-recents" class="widget">
  <h3>{% trans "Recent entries" %}</h3>
  {% get_recent_entries %}
</aside>
<aside id="widget-comments" class="widget">
  <h3>{% trans "Recent comments" %}</h3>
  {% get_recent_comments %}
</aside>
<aside id="widget-linkbacks" class="widget">
  <h3>{% trans "Recent linkbacks" %}</h3>
  {% get_recent_linkbacks %}
</aside>
<aside id="widget-randoms" class="widget">
  <h3>{% trans "Random entries" %}</h3>
  {% get_random_entries %}
</aside>
<aside id="widget-populars" class="widget">
  <h3>{% trans "Popular entries" %}</h3>
  {% get_popular_entries %}
</aside>
<aside id="widget-archives" class="widget">
  <h3>{% trans "Archives" %}</h3>
  {% get_archives_entries_tree %}
</aside>
{% if user.is_authenticated %}
<aside id="widget-tools" class="widget">
  <h3>{% trans "Tools" %}</h3>
  <ul>
    {% if perms.zinnia %}
    <li>
      <a href="{% url 'admin:app_list' 'zinnia' %}" title="{% trans "Dashboard" %}">
        {% trans "Dashboard" %}
      </a>
    </li>
    {% endif %}
    {% if perms.zinnia.add_entry %}
    <li>
      <a href="{% url 'admin:zinnia_entry_add' %}" title="{% trans "Post an entry" %}">
        {% trans "Post an entry" %}
      </a>
    </li>
    {% endif %}
    {% block admin-tools %}
    {% endblock admin-tools %}
    <li>
      <a href="{% url 'account_logout' %}" title="{% trans "Log out" %}">
        {% trans "Log out" %}
      </a>
    </li>
  </ul>
</aside>
{% endif %}
{% endblock sidebar %}

templates/zinnia/category_list.html
{% extends "zinnia/base.html" %}
{% load i18n %}
{% load mptt_tags %}

{% block meta-description %}{% trans "Category list" %}{% endblock meta-description %}

{% block title %}{% trans "Categories" %}{% endblock title %}

{% block body-class %}category-list{% endblock body-class %}

{% block content %}
<h1>{% trans "Category list" %}</h1>

<ul>
  {% for object in object_list %}
  <li>
    <a href="{{ object.get_absolute_url }}"
       title="{% blocktrans with category=object %}Show all entries in {{ category }}{% endblocktrans %}">{{ object }}</a>
    {% blocktrans count entry_count=object.count_entries_published %}{{ entry_count }} entry{% plural %}{{ entry_count }} entries{% endblocktrans %}
    {% if object.description %}<p>{{ object.description|striptags|safe }}</p>{% endif %}
  </li>
  {% empty %}
  <li>
    {% trans "No categories yet." %}
  </li>
  {% endfor %}
</ul>
{% endblock content %}

templates/zinnia/entry_archive.html
{% extends "zinnia/entry_list.html" %}
{% load i18n %}
{% load zinnia %}

{% block meta-description %}{% trans "Last entries" %}{% endblock meta-description %}

{% block title %}{% trans "Last entries" %}{% endblock title %}

{% block body-class %}{{ block.super }} archive index {% now "\y\e\a\r-Y \m\o\n\t\h-m \w\e\ek-W \d\a\y-d" %}{% endblock body-class %}

{% block slider %}
{% get_featured_entries template="zinnia/tags/entries_slider.html" %}
{% endblock slider %}

{% block content-related %}
{% if date_list %}
<h2>{% trans "Yearly archives" %}</h2>
<ul>
  {% for date in date_list %}
  <li>
    <a href="{% url 'zinnia:entry_archive_year' date|date:"Y" %}" rel="archives">{{ date|date:"Y" }}</a>
  </li>
  {% endfor %}
</ul>
{% endif %}
{% endblock content-related %}

templates/zinnia/entry_archive_day.html
{% extends "zinnia/entry_list.html" %}
{% load i18n %}
{% load zinnia %}

{% block meta-description %}{% trans "Archives" %} {{ day|date:"DATE_FORMAT" }}{% endblock meta-description %}

{% block title %}{% trans "Archives" %} {{ day|date:"DATE_FORMAT" }}{% endblock title %}

{% block body-class %}{{ block.super }} archive date day year-{{ day|date:"Y" }} month-{{ day|date:"m" }} week-{{ day|date:"W" }} day-{{ day|date:"d" }}{% endblock body-class %}

{% block content-title %}
<h1>{% trans "Archives" %} {{ day|date:"DATE_FORMAT" }}</h1>
{% endblock content-title %}

{% block content-related %}
{% if previous_day %}
<h3>{% trans "Previous day" %}</h3>
<p>
  <a href="{% url 'zinnia:entry_archive_day' previous_day|date:"Y" previous_day|date:"m" previous_day|date:"d" %}" rel="archives">{{ previous_day|date:"DATE_FORMAT" }}</a>
</p>
{% endif %}
{% if next_day %}
<h3>{% trans "Next day" %}</h3>
<p>
  <a href="{% url 'zinnia:entry_archive_day' next_day|date:"Y" next_day|date:"m" next_day|date:"d" %}" rel="archives">{{ next_day|date:"DATE_FORMAT" }}</a>
</p>
{% endif %}

<h3>{% trans "Archives" %}</h3>
<ul>
  <li>
    <a href="{% url 'zinnia:entry_archive_year' day|date:"Y" %}" rel="archives">{{ day|date:"Y" }}</a>
  </li>
  <li>
    <a href="{% url 'zinnia:entry_archive_week' day|date:"Y" day|week_number %}" rel="archives">
      {% blocktrans with year=day|date:"Y" week_number=day|week_number %}Week {{ week_number }} of {{ year }}{% endblocktrans %}
    </a>
  </li>
  {% if previous_month %}
  <li>
    <a href="{% url 'zinnia:entry_archive_month' previous_month|date:"Y" previous_month|date:"m" %}" rel="archives">{{ previous_month|date:"YEAR_MONTH_FORMAT" }}</a>
  </li>
  {% endif %}
  <li>
    <a href="{% url 'zinnia:entry_archive_month' day|date:"Y" day|date:"m" %}" rel="archives">{{ day|date:"YEAR_MONTH_FORMAT" }}</a>
  </li>
  {% if next_month %}
  <li>
    <a href="{% url 'zinnia:entry_archive_month' next_month|date:"Y" next_month|date:"m" %}" rel="archives">{{ next_month|date:"YEAR_MONTH_FORMAT" }}</a>
  </li>
  {% endif %}
</ul>
{% endblock content-related %}

templates/zinnia/entry_archive_today.html
{% extends "zinnia/entry_list.html" %}
{% load i18n %}

{% block meta-description %}{% trans "Today archives" %} {{ day|date:"DATE_FORMAT" }}{% endblock meta-description %}

{% block title %}{% trans "Today archives" %} {{ day|date:"DATE_FORMAT" }}{% endblock title %}

{% block body-class %}{{ block.super }} archive date today year-{{ day|date:"Y" }} month-{{ day|date:"m" }} week-{{ day|date:"W" }} day-{{ day|date:"d" }}{% endblock body-class %}

{% block content-title %}
<h1>{% trans "Today archives" %}</h1>
{% endblock content-title %}

{% block content-related %}
{% if previous_day %}
<h3>{% trans "Previous day" %}</h3>
<p>
  <a href="{% url 'zinnia:entry_archive_day' previous_day|date:"Y" previous_day|date:"m" previous_day|date:"d" %}" rel="archives">{{ previous_day|date:"DATE_FORMAT" }}</a>
</p>
{% endif %}

<h3>{% trans "Archives" %}</h3>
<ul>
  <li>
    <a href="{% url 'zinnia:entry_archive_year' day|date:"Y" %}" rel="archives">{{ day|date:"Y" }}</a>
  </li>
  {% if previous_month %}
  <li>
    <a href="{% url 'zinnia:entry_archive_month' previous_month|date:"Y" previous_month|date:"m" %}" rel="archives">{{ previous_month|date:"YEAR_MONTH_FORMAT" }}</a>
  </li>
  {% endif %}
  <li>
    <a href="{% url 'zinnia:entry_archive_month' day|date:"Y" day|date:"m" %}" rel="archives">{{ day|date:"YEAR_MONTH_FORMAT" }}</a>
  </li>
<ul>
{% endblock content-related %}

templates/zinnia/entry_archive_week.html
{% extends "zinnia/entry_list.html" %}
{% load i18n %}
{% load zinnia %}

{% block meta-description %}{% blocktrans with year=week|date:"Y" week_number=week|week_number %}Archives week {{ week_number }} of {{ year }}{% endblocktrans %}{% endblock meta-description %}

{% block title %}{% blocktrans with year=week|date:"Y" week_number=week|week_number %}Archives week {{ week_number }} of {{ year }}{% endblocktrans %}{% endblock title %}

{% block body-class %}{{ block.super }} archive date week year-{{ week|date:"Y" }} month-{{ week|date:"m" }} week-{{ week|week_number }}{% endblock body-class %}

{% block content-title %}
<h1>{% blocktrans with year=week|date:"Y" week_number=week|week_number %}Archives week {{ week_number }} of {{ year }}{% endblocktrans %}</h1>
<h2>{{ week|date:"DATE_FORMAT" }} - {{ week_end_day|date:"DATE_FORMAT" }}</h2>
{% endblock content-title %}

{% block content-related %}
{% if date_list %}
<h2>{% trans "Daily archives" %}</h2>
<ul>
  {% for date in date_list %}
  <li>
    <a href="{% url 'zinnia:entry_archive_day' date|date:"Y" date|date:"m" date|date:"d" %}" rel="archives">{{ date|date:"DATE_FORMAT" }}</a>
  </li>
  {% endfor %}
</ul>
{% endif %}
{% if previous_week %}
<h3>{% trans "Previous week" %}</h3>
<p>
  <a href="{% url 'zinnia:entry_archive_week' previous_week|date:"Y" previous_week|week_number %}" rel="archives">
    {% blocktrans with year=previous_week|date:"Y" week_number=previous_week|week_number %}Week {{ week_number }} of {{ year }}{% endblocktrans %}
  </a>
</p>
{% endif %}
{% if next_week %}
<h3>{% trans "Next week" %}</h3>
<p>
  <a href="{% url 'zinnia:entry_archive_week' next_week|date:"Y" next_week|week_number %}" rel="archives">
    {% blocktrans with year=next_week|date:"Y" week_number=next_week|week_number %}Week {{ week_number }} of {{ year }}{% endblocktrans %}
  </a>
</p>
{% endif %}
<h3>{% trans "Archives" %}</h3>
<ul>
  <li>
    <a href="{% url 'zinnia:entry_archive_year' week|date:"Y" %}" rel="archives">{{ week|date:"Y" }}</a>
  </li>
  <li>
    <a href="{% url 'zinnia:entry_archive_month' week|date:"Y" week|date:"m" %}" rel="archives">{{ week|date:"YEAR_MONTH_FORMAT" }}</a>
  </li>
<ul>
{% endblock content-related %}

templates/zinnia/entry_archive_year.html
{% extends "zinnia/entry_list.html" %}
{% load i18n %}

{% block meta-description %}{% trans "Archives" %} {{ year|date:"Y" }}{% endblock meta-description %}

{% block title %}{% trans "Archives" %} {{ year|date:"Y" }}{% endblock title %}

{% block body-class %}{{ block.super }} archive date year year-{{ year|date:"Y" }}{% endblock body-class %}

{% block content-title %}
<h1>{% trans "Archives" %} {{ year|date:"Y" }}</h1>
{% endblock content-title %}

{% block content-related %}
<h2>{% trans "Monthly archives" %}</h2>
<ul>
  {% for date in date_list %}
  <li>
    <a href="{% url 'zinnia:entry_archive_month' date|date:"Y" date|date:"m" %}" rel="archives">{{ date|date:"YEAR_MONTH_FORMAT" }}</a>
  </li>
  {% endfor %}
</ul>

{% if previous_year %}
<h3>{% trans "Previous year" %}</h3>
<p>
  <a href="{% url 'zinnia:entry_archive_year' previous_year|date:"Y" %}" rel="archives">{{ previous_year|date:"Y" }}</a>
</p>
{% endif %}
{% if next_year %}
<h3>{% trans "Next year" %}</h3>
<p>
  <a href="{% url 'zinnia:entry_archive_year' next_year|date:"Y" %}" rel="archives">{{ next_year|date:"Y" }}</a>
</p>
{% endif %}
{% endblock content-related %}

templates/zinnia/entry_form.html
{% extends "core/generic/generic_form.html" %}

{% load staticfiles %}

{% block js %}
    $('#id_content').markdownEditor({
        preview: true,
        imageLoadUrl: '{% url "blog:get_image_list" %}',
        uploadPath: '{% url 'blog:upload' %}',
        onPreview: function (content, callback) {
            callback( marked(content) );
        }
    });
{% endblock js %}

{% block scoped_css %}
    <style scoped>

    </style>
{% endblock %}

{% block head_extra_css %}
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/markdown-editor.css" %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block foot-extra-js %}
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/uploader.js" %}"></script>
    <script src="{% static 'js/markdown-editor.js' %}"></script>
    <script src="{% static 'ace/ace.js' %}"></script>
    <script src="{% static 'js/marked.min.js' %}"></script>
{% endblock %}

{% block modals %}
    <div id="dropzone" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog"
         aria-labelledby="myLargeModalLabel">
        <div class="modal-dialog modal-lg">
            <div id="container" class="modal-content">
                {% include 'blog/modal_body.html' %}
            </div>
        </div>
    </div>
{% endblock %}

templates/zinnia/entry_list.html
{% extends "zinnia/base.html" %}
{% load i18n %}
{% load zinnia %}

{% block meta-description %}{% spaceless %}
{% if category %}
{% if category.description %}
{{ category.description|striptags|safe }}
{% else %}
{% blocktrans with object=category %}The last entries categorized under {{ object }}{% endblocktrans %}
{% endif %}
{% endif %}

{% if tag %}
{% blocktrans with object=tag %}The last entries tagged with {{ object }}{% endblocktrans %}
{% endif %}

{% if author %}
{% blocktrans with object=author %}The last entries by {{ object }}{% endblocktrans %}
{% endif %}

{% endspaceless %}{% endblock meta-description %}

{% block meta-description-page %}{% if page_obj %}{% ifnotequal page_obj.number 1 %} {% blocktrans with object=page_obj.number %}page {{ object }}{% endblocktrans %}{% endifnotequal %}{% endif %}{% endblock meta-description-page %}

{% block title %}{% spaceless %}
{% if category %}
{% blocktrans with object=category %}Category {{ object }}{% endblocktrans %}
{% endif %}

{% if tag %}
{% blocktrans with object=tag %}Tag {{ object }}{% endblocktrans %}
{% endif %}

{% if author %}
{% blocktrans with object=author %}Author {{ object }}{% endblocktrans %}
{% endif %}

{% endspaceless %}{% endblock title %}

{% block title-page %}{% if page_obj %}{% ifnotequal page_obj.number 1 %} - {% blocktrans with object=page_obj.number %}Page {{ object }}{% endblocktrans %}{% endifnotequal %}{% endif %}{% endblock title-page %}

{% block link %}
  {{ block.super }}
  {% if category %}
    <link rel="alternate" type="application/rss+xml" title="{% blocktrans with object=category %}RSS feed of {{ object }}{% endblocktrans %}" href="{% url 'zinnia:category_feed' category.tree_path %}" />
  {% endif %}
  {% if tag %}
    <link rel="alternate" type="application/rss+xml" title="{% blocktrans with object=tag %}RSS feed of {{ object }}{% endblocktrans %}" href="{% url 'zinnia:tag_feed' tag.name %}" />
  {% endif %}
  {% if author %}
    <link rel="alternate" type="application/rss+xml" title="{% blocktrans with object=author %}RSS feed of {{ object }}{% endblocktrans %}" href="{% url 'zinnia:author_feed' author.get_username %}" />
  {% endif %}
{% endblock link %}

{% block body-class %}entry-list{% if page_obj %} paginated page-{{ page_obj.number }}{% endif %}{% if category %} category category-{{ category.slug }}{% endif %}{% if tag %} tag tag-{{ tag|slugify }}{% endif %}{% if author %} author author-{{ author|slugify }}{% endif %}{% endblock body-class %}

{% block content %}

{% block content-title %}
{% if category %}
<h1>{% blocktrans %}Category archives: {{ category }}{% endblocktrans %}</h1>
{% if category.description %}
<p>{{ category.description|striptags|safe }}</p>
{% endif %}
<p class="feed">
  <a href="{% url 'zinnia:category_feed' category.tree_path %}" title="{% blocktrans with object=category %}RSS feed of {{ object }}{% endblocktrans %}">
    {% blocktrans with object=category %}RSS feed of {{ object }}{% endblocktrans %}
  </a>
</p>
{% endif %}

{% if tag %}
<h1>{% blocktrans %}Tag archives: {{ tag }}{% endblocktrans %}</h1>
<p class="feed">
  <a href="{% url 'zinnia:tag_feed' tag.name %}" title="{% blocktrans with object=tag %}RSS feed of {{ object }}{% endblocktrans %}">
    {% blocktrans with object=tag %}RSS feed of {{ object }}{% endblocktrans %}
  </a>
</p>
{% endif %}

{% if author %}
<h1>{% blocktrans %}Author archives: {{ author }}{% endblocktrans %}</h1>
<p class="feed">
  <a href="{% url 'zinnia:author_feed' author.get_username %}" title="{% blocktrans with object=author %}RSS feed of {{ object }}{% endblocktrans %}">
    {% blocktrans with object=author %}RSS feed of {{ object }}{% endblocktrans %}
  </a>
</p>
{% endif %}
{% endblock content-title %}

{% block content-loop %}
{% for object in object_list %}
  {% zinnia_loop_template object.content_template as template %}
  {% include template with object_content=object.html_preview continue_reading=1 %}
{% empty %}
  <p class="info">
    <a href="{% url 'blog:entry_create' %}">{% trans "No entries yet." %}</a>
  </p>
{% endfor %}
{% endblock content-loop %}

{% block content-pagination %}
{% if is_paginated %}
  {% zinnia_pagination page_obj %}
{% endif %}
{% endblock content-pagination %}

{% block content-related %}
{% endblock content-related %}

{% endblock content %}

{% block admin-tools %}
  {% if category and perms.zinnia.change_category %}
  <li>
    <a href="{% url 'admin:zinnia_category_change' category.pk %}" title="{% trans "Edit the category" %}">
      {% trans "Edit the category" %}
    </a>
  </li>
  {% endif %}
  {% if tag and perms.tagging.change_tag %}
  <li>
    <a href="{% url 'admin:tagging_tag_change' tag.pk %}" title="{% trans "Edit the tag" %}">
      {% trans "Edit the tag" %}
    </a>
  </li>
  {% endif %}
  {% if author and perms.auth.change_user %}
  <li>
    <a href="{% url 'change'|user_admin_urlname author.pk %}" title="{% trans "Edit the author" %}">
      {% trans "Edit the author" %}
    </a>
  </li>
  {% endif %}
{% endblock admin-tools %}

templates/zinnia/entry_search.html
{% extends "zinnia/entry_list.html" %}
{% load i18n %}
{% load zinnia %}

{% block title %}{% blocktrans %}Search results for '{{ pattern }}'{% endblocktrans %}{% endblock title %}

{% block meta-description %}{% blocktrans %}Search results for '{{ pattern }}'{% endblocktrans %}{% endblock meta-description %}

{% block link %}
  {{ block.super }}
  {% if not error %}
  <link rel="alternate" type="application/rss+xml" title="{% blocktrans %}RSS feed of search results for '{{ pattern }}'{% endblocktrans %}" href="{% url 'zinnia:entry_search_feed' %}?pattern={{ pattern }}" />
  {% endif %}
{% endblock link %}

{% block body-class %}{{ block.super }} search {% if error %}search-error{% elif object_list %}search-results{% else %}search-no-results{% endif %}{% endblock body-class %}

{% block content-title %}
<h1>{% blocktrans %}Search results for '{{ pattern }}'{% endblocktrans %}</h1>

{% if error %}
<p class="error">{{ error }}</p>
{% else %}
<p class="feed">
  <a href="{% url 'zinnia:entry_search_feed' %}?pattern={{ pattern }}" title="{% blocktrans %}RSS feed of search results for '{{ pattern }}'{% endblocktrans %}">
    {% blocktrans %}RSS feed of search results for '{{ pattern }}'{% endblocktrans %}
  </a>
</p>
{% endif %}

{% if object_list %}
<p class="success">
  {% blocktrans count entry_count=paginator.count %}{{ entry_count }} entry found{% plural %}{{ entry_count }} entries found{% endblocktrans %}
</p>
{% endif %}

{% endblock content-title %}

{% block content-loop %}
{% if not error %}
{% for object in object_list %}
  {% zinnia_loop_template object.content_template as template %}
  {% include template with object_content=object.html_preview continue_reading=1 %}
{% empty %}
<p class="info">{% trans "Nothing found." %}</p>
{% endfor %}
{% endif %}
{% endblock content-loop %}

{% block content-related %}
<div class="search">
  {% include "zinnia/tags/search_form.html" %}
</div>
{% endblock content-related %}

templates/zinnia/login.html
{% extends "zinnia/base.html" %}
{% load i18n %}

{% block title %}{% trans "Login required" %}{% endblock title %}

{% block body-class %}login-required{% endblock body-class %}

{% block content %}
<h1>{% trans "Login required" %}</h1>

{% if form.errors %}
<p class="error">
  {% trans "Your username and password didn't match. Please try again." %}
</p>
{% endif %}
<p>
  {% trans "You need to be connected to view this entry." %}
</p>

<form method="post" action=".">
  {% csrf_token %}
  <table>
    <tr>
      <td>{{ form.username.label_tag }}</td>
      <td>{{ form.username }}</td>
    </tr>
    <tr>
      <td>{{ form.password.label_tag }}</td>
      <td>{{ form.password }}</td>
    </tr>
    <tr>
      <td colspan="2">
        <input type="hidden" name="next" value="." />
        <input type="submit" value="{% trans "Login" %}" />
      </td>
    </tr>
  </table>
</form>
{% endblock content %}

templates/zinnia/password.html
{% extends "zinnia/base.html" %}
{% load i18n %}

{% block title %}{% trans "Password required" %}{% endblock title %}

{% block body-class %}password-required{% endblock body-class %}

{% block content %}
<h1>{% trans "Password required" %}</h1>

{% if error %}
<p class="error">
  {% trans "The password provided is not valid. Please try again." %}
</p>
{% endif %}
<p>
  {% trans "You need to provide a password to view this entry." %}
</p>

<form method="post" action=".">
  {% csrf_token %}
  <table>
    <tr>
      <td><label for="id_password">{% trans "Password" %}</label></td>
      <td><input name="entry_password" id="id_password" type="password" /></td>
    </tr>
    <tr>
      <td colspan="2">
        <input type="submit" value="{% trans "Valid" %}" />
      </td>
    </tr>
  </table>
</form>
{% endblock content %}